### ISSUE TITLE
Could it work in Git Bash?

### ISSUE THREAD

**Issue by light049** [hakobera/nvmw#10]
It seems bat file doesn't work in Git Bash.
Or is there any other way to make it work in Git Bash?

thanks~

**Comment by amullins83** [comment]
In my experience, git bash doesn't run .bat files at all. It seems to interpret them as `sh` scripts and throws errors for nearly every line, including the obligatory `@echo off` at the beginning of most batch scripts (including nvmw.bat).

**Comment by hakobera** [comment]
@light049 @varemenos @amullins83 Sorry, nvmw does not support git bash.
If you use git bash in PowerShell, [ps-nvmw](https://github.com/aaronpowell/ps-nvmw) may help you.
