### ISSUE TITLE
Input Error: There is no script engine for file extension ".js".

### ISSUE THREAD

**Issue by crazy4groovy** [hakobera/nvmw#19]
Anyone know where this error is coming from? (Win7 x64)

```
C:\Windows\System32>nvmw install v0.10.24
Start installing Node v0.10.24
Microsoft (R) Windows Script Host Version 5.8
Copyright (C) Microsoft Corporation. All rights reserved.

Input Error: There is no script engine for file extension ".js".
Download C:\Users\user1\.nvmw\v0.10.24\node.exe from http://nodejs.org/dist/v0.10.24/node.exe failed
```

**Comment by andythecoderman** [comment]
Is there an alternative fix? I like having .js mapped to a editor vs. trying to run the script by default

**Comment by jdiapps** [comment]
I followed the link above, ran the regsvr32 commands, it still did not associate my .js files to the jscript.dll script host.  Whats the best way to register *.js extension with script host?
