### ISSUE TITLE
Missing npm v1.4.14 package

### ISSUE THREAD

**Issue by pmalouin** [hakobera/nvmw#27]
Trying to install node v0.10.29, but fails while trying to download npm from:
http://nodejs.org/dist/npm/npm-1.4.14.zip
Package does not exist. Maybe you would know why the package was not published? Maybe a new location or no longer distributed as a zip?

For sure, the console output from nvmw was not helpful in debugging this and it took me some time to find out what was happening.

> nvmw install v0.10.29
Start installing Node v0.10.29 (x64)
Start installing Node v0.10.29 (x64)
Microsoft (R) Windows Script Host Version 5.8
Copyright (C) Microsoft Corporation. All rights reserved.

> Download from http://nodejs.org/dist/v0.10.29/x64/node.exe, and save it as C:\Us
ers\Patrick\.nvmw\v0.10.29\node.exe
Done
Start install npm
Download file from https://raw.githubusercontent.com/joyent/node/v0.10.29/deps/npm/package.json
package.json
Content length is 3.58kb
Download 100%, 3.58kb / 3.58kb, 1.75mb/s ...
Donwload done
Download file from http://nodejs.org/dist/npm/npm-1.4.14.zip
npm-1.4.14.zip
Download npm 1.4.14 is done **Hangs at this line for about 2 minutes**
Microsoft (R) Windows Script Host Version 5.8
Copyright (C) Microsoft Corporation. All rights reserved.

> C:\Users\Patrick\.nvmw\v0.10.29
The process cannot access the file because it is being used by another process.

**Comment by hakobera** [comment]
@pmalouin @heri16 Sorry for late response. This issue is fixed by #36
