### ISSUE TITLE
nvmw install node error: 另一个程序正在使用此文件，进程无法访问。

### ISSUE THREAD

**Issue by yuqigong** [hakobera/nvmw#29]
D:\Users\gongyuqi>nvmw install v0.10.29
Start installing Node v0.10.29 (x64)
Start installing Node v0.10.29 (x64)
子目录或文件 D:\Users\gongyuqi\.nvmw\v0.10.29 已经存在。
Microsoft (R) Windows Script Host Version 5.8
版权所有(C) Microsoft Corporation 1996-2001。保留所有权利。

Download from http://nodejs.org/dist/v0.10.29/x64/node.exe, and save it as D:\Us
ers\gongyuqi\.nvmw\v0.10.29\node.exe
Done
Start install npm
Download file from https://raw.githubusercontent.com/joyent/node/v0.10.29/deps/n
pm/package.json
package.json
Content length is 3.58kb
Download 100%, 3.58kb / 3.58kb, 511.86kb/s ...
Donwload done
Download file from http://nodejs.org/dist/npm/npm-1.4.14.zip
npm-1.4.14.zip
Download npm 1.4.14 is done
Microsoft (R) Windows Script Host Version 5.8
版权所有(C) Microsoft Corporation 1996-2001。保留所有权利。

D:\Users\gongyuqi\.nvmw\v0.10.29
另一个程序正在使用此文件，进程无法访问。

**Comment by hakobera** [comment]
This is fixed by #36
