### ISSUE TITLE
download link error

### ISSUE THREAD

**Issue by gusyang** [hakobera/nvmw#60]
for v4.1.0,
when use nvmw install v4.1.0, the bat file build link is https://nodejs.org/dist/v4.1.0/x64/node.exe
but real link is "https://nodejs.org/dist/v4.1.0/win-x64/node.exe"

**Comment by littleben93** [comment]
The same issue.
I changed this string
`set NODE_EXE_URL=%NVMW_NODEJS_ORG_MIRROR%/%NODE_VERSION%/x64/node.exe`
to 
`set NODE_EXE_URL=%NVMW_NODEJS_ORG_MIRROR%/%NODE_VERSION%/**win-x64**/node.exe` and it works.
